config/routes.rb
MyApp::Application.routes.draw do

  resources :recipes

end

app/models/author.rb
# To change this template, choose Tools | Templates
# and open the template in the editor.

class Author
  include MongoMapper::Document
    key :name, String, :required => true
    many :recipes
end

app/models/recipe.rb
class Recipe
  include MongoMapper::Document
    key :name, String, :required => true
    key :priority, Integer
    belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params[:recipe])
    if @recipe.save
      flash[:notice] = "Successfully created recipe."
      redirect_to recipe_path(@recipe)
    else
      render :action => 'new'
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def destroy
     Recipe.destroy(params[:id])
     redirect_to recipes_path
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      flash[:notice] = "Successfully updated recipe."
      redirect_to recipe_path(@recipe)
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :priority %><br />
    <%= f.select :priority, [1,2,3,4,5] %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/recipes/edit.html.erb
<% title "Edit Recipe" %>

<%= render('form') %>

<p><%= link_to "Back to List", recipes_path %></p>

app/views/recipes/index.html.erb
<% title "Recipes" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for recipe in @recipes %>
    <tr>
      <td><%= link_to recipe.name, recipe_path(recipe) %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Recipe", new_recipe_path %></p>

app/views/recipes/new.html.erb
<% title "New Recipe" %>

<%= render('form') %>

<p><%= link_to "Back to List", recipes_path %></p>

app/views/recipes/show.html.erb
<% title "Recipe" %>
<p>
  <strong>Name:</strong>
  <%=h @recipe.name %>
</p>
<p>
  <strong>Priority:</strong>
  <%=h @recipe.priority %>
</p>
<p>
  <%= link_to "Edit", edit_recipe_path(@recipe) %> |
  <%= link_to "Destroy", @recipe, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", recipes_path %>
</p>